package stepDefs;

import io.cucumber.java.en.*;
import pages.Profile;
import configs.loadProps;
import java.util.logging.Logger;

/**
 * Step Definitions for Profile
 * Generated by AI Automation CLI - Enhanced with Configuration Management
 */
public class ProfileSteps {
    private static final Logger log = Logger.getLogger(ProfileSteps.class.getName());

    @Given("the application is ready")
    public void applicationIsReady() {
        log.info("📋 Application ready");
        log.info("🔧 Base URL: " + Profile.getBaseUrl());
        log.info("⏱️ Default Timeout: " + Profile.getDefaultTimeout() + "ms");
        log.info("🎥 Recording Enabled: " + Profile.isRecordingEnabled());
        log.info("📸 Screenshots Enabled: " + Profile.isScreenshotsEnabled());
    }

    @Given("user navigates to profile page")
    public void userNavigatesToProfilePage() {
        log.info("🌐 Navigating to profile page using configured URL");
        Profile.navigateToProfilePage();
    }

    @Then("profile page should be loaded")
    public void profilePageShouldBeLoaded() {
        log.info("✅ Verifying profile page is loaded");
        Profile.verifyPageLoaded();
    }

    @When("user enters {string} in firstname field")
    public void userEntersFirstname(String firstname) {
        log.info("📝 Entering firstname: " + firstname);
        // Get locator from config if available, otherwise use default
        String locator = loadProps.getProperty("profile.firstname.locator");
        if (locator == null) {
            locator = "input[name='firstname']"; // Default locator
        }
        Profile.firstname(locator, firstname);
    }

    @When("user enters {string} in email field")
    public void userEntersEmail(String email) {
        log.info("📧 Entering email: " + email);
        // Get locator from config if available, otherwise use default
        String locator = loadProps.getProperty("profile.email.locator");
        if (locator == null) {
            locator = "input[name='email']"; // Default locator
        }
        Profile.email(locator, email);
    }

    @When("user clicks save button")
    public void userClicksSave() {
        log.info("💾 Clicking save button");
        // Get locator from config if available, otherwise use default
        String locator = loadProps.getProperty("profile.save.locator");
        if (locator == null) {
            locator = "button[type='submit']"; // Default locator
        }
        Profile.save(locator);
    }

    // TODO: Add your step definitions here based on scenarios
    // Example:
    // @Given("User is on page")
    // public void userIsOnPage() {
    //     ProfilePage.navigateTo("/url");
    // }
}
