package pages;

import configs.TimeoutConfig;
import configs.loadProps;
import org.testng.Assert;
import java.util.logging.Logger;

/**
 * USer can update the profile details like firstname,lastname, and email address also you can choose lunguage and landing page from dropdown options
 * Generated by AI Automation CLI
 */
public class Profile extends BasePage {
    private static final Logger log = Logger.getLogger(Profile.class.getName());

    // Load configurations from properties file
    private static final String BASE_URL = loadProps.getProperty("URL");
    private static final String PROFILE_URL_PART = "/profile";

    public Profile() {
        super();
    }

    /**
     * Navigate to profile page using configured base URL
     */
    public static void navigateToProfilePage() {
        if (BASE_URL != null) {
            log.info("🌐 Navigating to profile page: " + BASE_URL + PROFILE_URL_PART);
            navigateTo(BASE_URL + PROFILE_URL_PART);
        } else {
            log.warning("⚠️ BASE_URL not configured in properties file");
        }
    }

    /**
     * Update firstname field
     * @param locator Element locator
     * @param text Text to enter
     */
    public static void firstname(String locator, String text) {
        log.info("🎯 Entering firstname");
        long startTime = System.currentTimeMillis();
        enterText(locator, text);
        long duration = System.currentTimeMillis() - startTime;
        log.info("⏱️ Action completed in " + duration + "ms");
        TimeoutConfig.shortWait();
        log.info("✅ Firstname entered successfully");
    }

    /**
     * Update email field
     * @param locator Element locator
     * @param text Email address to enter
     */
    public static void email(String locator, String text) {
        log.info("🎯 Entering email");
        long startTime = System.currentTimeMillis();
        enterText(locator, text);
        long duration = System.currentTimeMillis() - startTime;
        log.info("⏱️ Action completed in " + duration + "ms");
        TimeoutConfig.shortWait();
        log.info("✅ Email entered successfully");
    }

    /**
     * Click save button to submit profile changes
     * @param locator Element locator
     */
    public static void save(String locator) {
        log.info("🎯 Clicking save button");
        long startTime = System.currentTimeMillis();
        clickOnElement(locator);
        long duration = System.currentTimeMillis() - startTime;
        log.info("⏱️ Action completed in " + duration + "ms");
        TimeoutConfig.shortWait();
        log.info("✅ Save completed successfully");
    }

    /**
     * Verify profile page is loaded using configured URL
     */
    public static void verifyPageLoaded() {
        log.info("🔍 Verifying profile page loaded");
        Assert.assertTrue(isUrlContains(PROFILE_URL_PART), "Profile page URL verification failed");
        log.info("✓ Profile page verified");
    }

    /**
     * Verify profile page is loaded with custom URL part
     */
    protected static void verifyPageLoaded(String expectedUrlPart) {
        log.info("🔍 Verifying page loaded");
        Assert.assertTrue(isUrlContains(expectedUrlPart), "Page URL verification failed");
        log.info("✓ Page verified");
    }

    /**
     * Get configured base URL from properties
     */
    public static String getBaseUrl() {
        return BASE_URL;
    }

    /**
     * Get default timeout from configuration
     */
    public static int getDefaultTimeout() {
        String timeout = loadProps.getProperty("DefaultTimeout");
        return timeout != null ? Integer.parseInt(timeout) : 30000;
    }

    /**
     * Check if recording mode is enabled from configuration
     */
    public static boolean isRecordingEnabled() {
        String recording = loadProps.getProperty("Recording_Mode");
        return recording != null && Boolean.parseBoolean(recording);
    }

    /**
     * Check if screenshots are enabled from configuration
     */
    public static boolean isScreenshotsEnabled() {
        String screenshots = loadProps.getProperty("Screenshots_Mode");
        return screenshots != null && Boolean.parseBoolean(screenshots);
    }

}
